import { Tabs } from 'expo-router';
import { StatusBar, StyleSheet, Platform } from 'react-native';

export default function Layout() {
  return (
    <>
      <StatusBar barStyle="dark-content" backgroundColor="#F5EDDC" />
      <Tabs
        screenOptions={{
          headerShown: false,
          tabBarStyle: styles.tabBar,
          tabBarActiveTintColor: '#F5EDDC',
          tabBarInactiveTintColor: '#5C7F71', // Sage Green
          tabBarActiveBackgroundColor: '#181818',
          tabBarInactiveBackgroundColor: '#181818',
          tabBarLabelStyle: styles.tabLabel,
          tabBarIconStyle: { display: 'none' }, // Constructivism prefers typography over icons
          tabBarItemStyle: styles.tabItem,
        }}>
        <Tabs.Screen
          name="index"
          options={{
            title: 'APPARATUS',
          }}
        />
        <Tabs.Screen
          name="analytics"
          options={{
            title: 'ANALYTICS',
          }}
        />
        <Tabs.Screen
          name="dossier"
          options={{
            title: 'DOSSIER',
          }}
        />
        <Tabs.Screen
          name="explore"
          options={{
            href: null, // Hide explore tab that was generated by expo
          }}
        />
      </Tabs>
    </>
  );
}

const styles = StyleSheet.create({
  tabBar: {
    backgroundColor: '#181818',
    borderTopWidth: 6,
    borderTopColor: '#181818',
    height: Platform.OS === 'ios' ? 80 : 70,
    paddingBottom: Platform.OS === 'ios' ? 20 : 0,
  },
  tabLabel: {
    fontFamily: Platform.OS === 'ios' ? 'Helvetica Neue' : 'sans-serif',
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 1,
    textTransform: 'uppercase',
    paddingBottom: 15,
  },
  tabItem: {
    justifyContent: 'center',
    alignItems: 'center',
    borderRightWidth: 2, // Slight separator between tabs
    borderColor: '#5C7F71',
  }
});
